allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@swc/core': true
  aws-sdk: true
  better-sqlite3: true
  electron-winstaller: true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  prisma: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - aws-sdk
  - better-sqlite3
  - electron
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - prisma
  - unrs-resolver
