import { ColumnDef } from '../../shared/components/base-table/column-def.interface';

export const UNIVERSE_COLUMNS: ColumnDef[] = [
  {
    field: 'vol',
    header: 'Vol',
    tooltip: 'Volatility',
    width: 50,
  },
  {
    field: 'svol',
    header: 'SVol',
    tooltip: 'Short-Term Volatility',
    width: 50,
  },
  { field: 'symbol', header: 'Symbol', sortable: true, width: 80 },
  {
    field: 'risk_group',
    header: 'Risk Group',
    sortable: true,
    width: 90,
  },
  {
    field: 'distribution',
    header: 'Distribution',
    type: 'number',
    editable: true,
    width: 120,
  },
  {
    field: 'distributions_per_year',
    header: 'Dist/Year',
    type: 'number',
    editable: true,
    width: 80,
  },
  {
    field: 'yield_percent',
    header: 'Yield %',
    type: 'number',
    sortable: true,
    width: 90,
  },
  {
    field: 'avg_purchase_yield_percent',
    header: 'Avg Purch Yield %',
    type: 'number',
    sortable: true,
    width: 120,
  },
  {
    field: 'last_price',
    header: 'Last Price',
    type: 'currency',
    width: 90,
  },
  {
    field: 'ex_date',
    header: 'Ex-Date',
    type: 'date',
    editable: true,
    sortable: true,
    width: 175,
  },
  {
    field: 'most_recent_sell_date',
    header: 'Mst Rcnt Sll Dt',
    type: 'date',
    sortable: true,
    width: 110,
  },
  {
    field: 'most_recent_sell_price',
    header: 'Mst Rcnt Sell $',
    type: 'currency',
    sortable: true,
    width: 110,
  },
  { field: 'position', header: 'Position', type: 'number', width: 140 },
  { field: 'expired', header: 'Expired', width: 100 },
  { field: 'actions', header: 'Actions', width: 70 },
];
