#!/bin/bash
# scripts/update-service-docs.sh
# Automatically update service documentation from AWS

set -e

echo "📋 Updating service documentation..."

# Ensure we're in the right directory
cd "$(dirname "$0")/.."

# Check if AWS CLI is available
if ! command -v aws &> /dev/null; then
    echo "❌ AWS CLI not found. Please install AWS CLI first."
    exit 1
fi

# Create directories if they don't exist
mkdir -p docs/operations

# Check AWS credentials
if ! aws sts get-caller-identity > /dev/null 2>&1; then
    echo "❌ AWS credentials not configured or invalid."
    echo "Please run 'aws configure' or set AWS environment variables."
    exit 1
fi

echo "🔍 Gathering ECS service information..."
# Generate ECS service information
if aws ecs list-clusters --query 'clusterArns' --output text | grep -q 'rms'; then
    CLUSTER_NAME=$(aws ecs list-clusters --query 'clusterArns' --output text | grep 'rms' | head -n1 | xargs basename)
    
    if [ -n "$CLUSTER_NAME" ]; then
        echo "📊 Found cluster: $CLUSTER_NAME"
        aws ecs describe-services \
            --cluster "$CLUSTER_NAME" \
            --services $(aws ecs list-services --cluster "$CLUSTER_NAME" --query 'serviceArns[]' --output text | head -10) \
            --query 'services[*].{Name:serviceName,Status:status,TaskDefinition:taskDefinition,DesiredCount:desiredCount,RunningCount:runningCount,PendingCount:pendingCount}' \
            --output table > docs/operations/current-services.txt 2>/dev/null || echo "No services found or error retrieving services" > docs/operations/current-services.txt
    else
        echo "No RMS clusters found" > docs/operations/current-services.txt
    fi
else
    echo "No ECS clusters found" > docs/operations/current-services.txt
fi

echo "🗄️ Gathering RDS information..."
# Generate RDS information
aws rds describe-db-instances \
    --query 'DBInstances[*].{Identifier:DBInstanceIdentifier,Status:DBInstanceStatus,Engine:Engine,Version:EngineVersion,Class:DBInstanceClass,Storage:AllocatedStorage}' \
    --output table > docs/operations/current-databases.txt 2>/dev/null || echo "No RDS instances found or error retrieving databases" > docs/operations/current-databases.txt

echo "⚖️ Gathering Load Balancer information..."
# Generate ALB information
aws elbv2 describe-load-balancers \
    --query 'LoadBalancers[*].{Name:LoadBalancerName,State:State.Code,Type:Type,Scheme:Scheme,DNS:DNSName}' \
    --output table > docs/operations/current-load-balancers.txt 2>/dev/null || echo "No load balancers found or error retrieving load balancers" > docs/operations/current-load-balancers.txt

echo "☁️ Gathering CloudFront information..."
# Generate CloudFront information
aws cloudfront list-distributions \
    --query 'DistributionList.Items[*].{Id:Id,DomainName:DomainName,Status:Status,Comment:Comment}' \
    --output table > docs/operations/current-cloudfront.txt 2>/dev/null || echo "No CloudFront distributions found or error retrieving distributions" > docs/operations/current-cloudfront.txt

echo "🪣 Gathering S3 bucket information..."
# Generate S3 bucket information
aws s3api list-buckets \
    --query 'Buckets[*].{Name:Name,CreationDate:CreationDate}' \
    --output table > docs/operations/current-s3-buckets.txt 2>/dev/null || echo "No S3 buckets found or error retrieving buckets" > docs/operations/current-s3-buckets.txt

# Generate service summary document
cat > docs/operations/service-summary.md << EOF
# AWS Services Summary

**Last Updated**: $(date)  
**Generated By**: Automated Service Documentation Update

## ECS Services

\`\`\`
$(cat docs/operations/current-services.txt)
\`\`\`

## RDS Databases

\`\`\`
$(cat docs/operations/current-databases.txt)
\`\`\`

## Load Balancers

\`\`\`
$(cat docs/operations/current-load-balancers.txt)
\`\`\`

## CloudFront Distributions

\`\`\`
$(cat docs/operations/current-cloudfront.txt)
\`\`\`

## S3 Buckets

\`\`\`
$(cat docs/operations/current-s3-buckets.txt)
\`\`\`

## Summary Statistics

- **ECS Services**: $(cat docs/operations/current-services.txt | grep -c '|' | grep -v '^0$' || echo "0")
- **RDS Instances**: $(cat docs/operations/current-databases.txt | grep -c '|' | grep -v '^0$' || echo "0")
- **Load Balancers**: $(cat docs/operations/current-load-balancers.txt | grep -c '|' | grep -v '^0$' || echo "0")
- **CloudFront Distributions**: $(cat docs/operations/current-cloudfront.txt | grep -c '|' | grep -v '^0$' || echo "0")
- **S3 Buckets**: $(cat docs/operations/current-s3-buckets.txt | grep -c '|' | grep -v '^0$' || echo "0")
- **Last Update**: $(date)

---
*This document is automatically generated. Do not edit manually.*
EOF

echo "✅ Service documentation updated successfully"
echo "📁 Files updated:"
echo "   - docs/operations/current-services.txt"
echo "   - docs/operations/current-databases.txt"
echo "   - docs/operations/current-load-balancers.txt"
echo "   - docs/operations/current-cloudfront.txt"
echo "   - docs/operations/current-s3-buckets.txt"
echo "   - docs/operations/service-summary.md"