#!/bin/bash
# scripts/update-infra-docs.sh
# Automatically update infrastructure documentation from Terraform state

set -e

echo "🏗️  Updating infrastructure documentation..."

# Ensure we're in the right directory
cd "$(dirname "$0")/.."

# Check if terraform is available
if ! command -v terraform &> /dev/null; then
    echo "❌ Terraform not found. Please install Terraform first."
    exit 1
fi

# Check if jq is available
if ! command -v jq &> /dev/null; then
    echo "❌ jq not found. Please install jq first."
    exit 1
fi

# Create directories if they don't exist
mkdir -p docs/infrastructure

# Navigate to infrastructure directory
if [ ! -d "apps/infrastructure" ]; then
    echo "❌ Infrastructure directory not found at apps/infrastructure"
    exit 1
fi

cd apps/infrastructure

# Initialize terraform if needed
if [ ! -f ".terraform.lock.hcl" ]; then
    echo "🔧 Initializing Terraform..."
    terraform init
fi

# Generate current state documentation
echo "📊 Generating current state documentation..."
terraform output -json > ../../docs/infrastructure/current-state.json 2>/dev/null || echo '{}' > ../../docs/infrastructure/current-state.json

# Generate resource inventory
echo "📋 Generating resource inventory..."
terraform state list > ../../docs/infrastructure/resource-inventory.txt 2>/dev/null || echo "No resources in state" > ../../docs/infrastructure/resource-inventory.txt

# Generate cost estimates (plan without applying)
echo "💰 Generating cost estimates..."
terraform plan -out=plan.out -detailed-exitcode > /dev/null 2>&1 || true

if [ -f "plan.out" ]; then
    terraform show -json plan.out | jq '.planned_values.root_module.resources[] | select(.values != null) | {type: .type, name: .name, values: .values}' > ../../docs/infrastructure/planned-resources.json 2>/dev/null || echo '[]' > ../../docs/infrastructure/planned-resources.json
    rm -f plan.out
else
    echo '[]' > ../../docs/infrastructure/planned-resources.json
fi

# Generate infrastructure summary
cd ../..
cat > docs/infrastructure/infrastructure-summary.md << EOF
# Infrastructure Summary

**Last Updated**: $(date)  
**Generated By**: Automated Documentation Update

## Current State

$(if [ -s "docs/infrastructure/current-state.json" ] && [ "$(cat docs/infrastructure/current-state.json)" != "{}" ]; then
    echo "### Terraform Outputs"
    echo "\`\`\`json"
    cat docs/infrastructure/current-state.json
    echo "\`\`\`"
else
    echo "No Terraform outputs available."
fi)

## Resource Inventory

\`\`\`
$(cat docs/infrastructure/resource-inventory.txt)
\`\`\`

## Total Resources

- **Total Resources**: $(cat docs/infrastructure/resource-inventory.txt | wc -l)
- **Last State Update**: $(date)

EOF

echo "✅ Infrastructure documentation updated successfully"
echo "📁 Files updated:"
echo "   - docs/infrastructure/current-state.json"
echo "   - docs/infrastructure/resource-inventory.txt"
echo "   - docs/infrastructure/planned-resources.json"
echo "   - docs/infrastructure/infrastructure-summary.md"